global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'log-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['log-producer:8080']
    scrape_interval: 10s

  - job_name: 'log-consumers'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
          - 'log-consumer-1:8080'
          - 'log-consumer-2:8080'
          - 'log-consumer-3:8080'
    scrape_interval: 10s

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9999']
    scrape_interval: 15s